# Generated by Django 5.1.1 on 2024-12-20 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_geeksmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
